name: Next.js CI/CD

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latestW
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      KINDE_CLIENT_ID: ${{ secrets.KINDE_CLIENT_ID }}
      KINDE_CLIENT_SECRET: ${{ secrets.KINDE_CLIENT_SECRET }}
      KINDE_ISSUER_URL: ${{ secrets.KINDE_ISSUER_URL }}
      KINDE_SITE_URL: ${{ secrets.KINDE_SITE_URL }}
      KINDE_POST_LOGIN_REDIRECT_URL: ${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }}
      KINDE_POST_LOGOUT_REDIRECT_URL: ${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run linting
      run: npm run lint

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test