name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test:
    name: Lint • Typecheck • Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Prisma generate
        run: npx prisma generate
        # If you need a database URL for generators, add env:
        # env:
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build
        env:
          # Add any build-time env vars your app needs here
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # NEXT_PUBLIC_* variables don't need to be secrets
          NODE_ENV: production
